# Site settings
title: Ling Chen
description: 'Computational biologist specialized in machine learning of genomics'
url: 'https://lingchen42.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ling Chen'
  email: ling.chen@vanderbilt.edu
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
  github_username:  lingchen42
  linkedin_username:  lingchen42

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
